### ISSUE TITLE
Does not work in Blender 3.0.0 release candidate

### ISSUE THREAD

**Issue by cstfan** [Shahzod114/Blender-BakeLab2#21]
Under the release candidate of Blender 3.0.0 there is this message :

Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.0.0-candidate+v30.2fb8c6805a98-windows.amd64-release\3.0\scripts\addons\Blender-BakeLab2-master\bakelab_bake.py", line 875, in modal
    result = next(self.BakeCrt)
  File "C:\Program Files\Blender Foundation\blender-3.0.0-candidate+v30.2fb8c6805a98-windows.amd64-release\3.0\scripts\addons\Blender-BakeLab2-master\bakelab_bake.py", line 631, in Bake
    self.save_defaults(context)
  File "C:\Program Files\Blender Foundation\blender-3.0.0-candidate+v30.2fb8c6805a98-windows.amd64-release\3.0\scripts\addons\Blender-BakeLab2-master\bakelab_bake.py", line 80, in save_defaults
    self.default_use_pass_ao       = bake_settings.use_pass_ambient_occlusion
AttributeError: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'
